### PR TITLE
can add additional config items

### PR DESCRIPTION
**Pull request by tracyatrf**
Hoping to be able to add custom fields to the moose configuration.

### CODE REVIEW

**Comment by hungryed** [comment]
I'm curious as to the use case for this.

This seems like a feature request of the gem. All of the configuration items are used within moose itself. Stepping outside of the scope of its own internal knowledge seems like we would be tying this to a product instead of being abstract

**Comment by tracyatrf** [comment]
I have pages that inherit from moose page full, and conditionally append a feature flag parameter at the end of the url by overriding the `replaced_path` method, so you can run the suite with a feature flag turned on. I figured the best place to store information about the feature flag would be in the moose config with the other config options.

**Comment by hungryed** [comment]
_and conditionally append a feature flag parameter at the end of the url by overriding the replaced_path method_

Instead of overriding the `replaced_path` method, you could override `_path`

you could something like:
```ruby
class MyPage < Moose::Page::Full
  initial_attributes(
    include_feature_flag: false
  )

  def _path
    return super + "?myFeatureFlag=true" if include_feature_flag
    super
  end
end
```

This may be a vague over simplification but does that also address the use case for what you mentioned?

Configuration options should really only span the space that this gem contains. It becomes harder to  include those options as command line flags if you can dynamically append to those. That also means we are reaching outside of the space that this gem occupies

**Comment by tracyatrf** [comment]
So what I am doing is taking in a feature flag id from the command line like `FF=12334`
and it will append it like `?ff=12334.`
I guess I am trying to figure out the best place to stick that config option.

But yeah, ^ that is basically what I am doing.

The reason I went with replaced path was because I wanted to hook in after moose did whatever with params, and then decide whether I need to give it a `?ff=` or `&ff=`

**Comment by hungryed** [comment]
So in that case you could do something to the effect of:

```ruby
class MyPage < Moose::Page::Full
  def feature_flag
    ENV["FF"]
  end

  def _path
    return super + "?ff=#{feature_flag}" if feature_flag
    super
  end
end
```

that would append the feature flag to the path in a manor that would handle seating of the value

if you wanted to do it before the build process:

```ruby
class MyPage < Moose::Page::Full
  if feature_flag = ENV["FF"]
    self.path = "/path/to/page?ff=#{feature_flag}"
  else
    self.path = "/path/to/page"
  end
end
```

At some point what we probably really want is to be able to store arbitrary state on the runner object that is passed around. and then we want to pass that runner into the page objects so that we have some ability to fetch details

**Pull request closed without merging**
